version: '3.8'
services:
  product_db:
    image: mongo
    container_name: product_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - .docker/product_db:/data/db
    ports:
      - '27017:27017'
    networks:
      - mongo_network
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_SERVER=product_db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=user
    links:
      - product_db
    volumes:
      - .docker/mongo_express:/data/db
    depends_on:
      - product_db
    networks:
      - mongo_network
    ports:
      - '8081:8081'
    restart: unless-stopped
networks:
  mongo_network:
    driver: bridge
    name: mongo_network

